apiVersion: v1
kind: Service
metadata:
  name: api-service-nodeport-service
  labels:
    app: api-service
  namespace: api-service  
spec:
  type: LoadBalancer
  selector:
    app: api-service
  ports:
    - port: 80
      targetPort: 5000
